[package]
name = "backend"
version = "0.1.0"
edition = "2021"


[dependencies]
poem = "3.0.0"
tokio = { version = "1.37.0", features = ["full"] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
